{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello World\n",
      "Python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]\n",
      "Python version info: sys.version_info(major=3, minor=10, micro=10, releaselevel='final', serial=0)\n"
     ]
    }
   ],
   "source": [
    "#!../input/RDS/bin/ python3\n",
    "\n",
    "print(\"Hello World\")\n",
    "\n",
    "import sys\n",
    "\n",
    "print(\"Python version:\", sys.version)\n",
    "print(\"Python version info:\", sys.version_info)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): failed\n",
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 161, in conda_http_errors\n",
      "        yield\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 127, in repodata\n",
      "        response.raise_for_status()\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n",
      "        raise HTTPError(http_error_msg, response=self)\n",
      "    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/rapidsai/linux-64/current_repodata.json\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/requests/models.py\", line 971, in json\n",
      "        return complexjson.loads(self.text, **kwargs)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/simplejson/__init__.py\", line 514, in loads\n",
      "        return _default_decoder.decode(s)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/simplejson/decoder.py\", line 386, in decode\n",
      "        obj, end = self.raw_decode(s)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/simplejson/decoder.py\", line 416, in raw_decode\n",
      "        return self.scan_once(s, idx=_w(s, idx).end())\n",
      "    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/exceptions.py\", line 1132, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/cli/main.py\", line 69, in main_subshell\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py\", line 122, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/notices/core.py\", line 121, in wrapper\n",
      "        return func(*args, **kwargs)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/cli/main_install.py\", line 20, in execute\n",
      "        install(args, parser, 'install')\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/cli/install.py\", line 264, in install\n",
      "        unlink_link_transaction = solver.solve_for_transaction(\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/solve.py\", line 134, in solve_for_transaction\n",
      "        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/solve.py\", line 177, in solve_for_diff\n",
      "        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/solve.py\", line 282, in solve_final_state\n",
      "        ssc = self._collect_all_metadata(ssc)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/common/io.py\", line 84, in decorated\n",
      "        return f(*args, **kwds)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/solve.py\", line 449, in _collect_all_metadata\n",
      "        index, r = self._prepare(prepared_specs)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/solve.py\", line 1064, in _prepare\n",
      "        reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/index.py\", line 267, in get_reduced_index\n",
      "        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 169, in query_all\n",
      "        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))\n",
      "      File \"/opt/conda/lib/python3.10/concurrent/futures/_base.py\", line 621, in result_iterator\n",
      "        yield _result_or_cancel(fs.pop())\n",
      "      File \"/opt/conda/lib/python3.10/concurrent/futures/_base.py\", line 319, in _result_or_cancel\n",
      "        return fut.result(timeout)\n",
      "      File \"/opt/conda/lib/python3.10/concurrent/futures/_base.py\", line 458, in result\n",
      "        return self.__get_result()\n",
      "      File \"/opt/conda/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n",
      "        raise self._exception\n",
      "      File \"/opt/conda/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n",
      "        result = self.fn(*self.args, **self.kwargs)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 158, in subdir_query\n",
      "        return tuple(\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 174, in query\n",
      "        self.load()\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 264, in load\n",
      "        _internal_state = self._load()\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py\", line 366, in _load\n",
      "        raw_repodata_str = self._repo.repodata(cache.state)  # type: ignore\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 120, in repodata\n",
      "        with conda_http_errors(self._url, filename):\n",
      "      File \"/opt/conda/lib/python3.10/contextlib.py\", line 153, in __exit__\n",
      "        self.gen.throw(typ, value, traceback)\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py\", line 208, in conda_http_errors\n",
      "        raise RepodataIsEmpty(\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/conda/exceptions.py\", line 462, in __init__\n",
      "        body = response.json()\n",
      "      File \"/opt/conda/lib/python3.10/site-packages/requests/models.py\", line 975, in json\n",
      "        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n",
      "    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "\n",
      "`$ /opt/conda/bin/conda install python==3.7.15`\n",
      "\n",
      "  environment variables:\n",
      "                 CIO_TEST=<not set>\n",
      "        CONDA_DEFAULT_ENV=base\n",
      "                CONDA_EXE=/opt/conda/bin/conda\n",
      "             CONDA_PREFIX=/opt/conda\n",
      "    CONDA_PROMPT_MODIFIER=(base)\n",
      "         CONDA_PYTHON_EXE=/opt/conda/bin/python\n",
      "               CONDA_ROOT=/opt/conda\n",
      "              CONDA_SHLVL=1\n",
      "           CURL_CA_BUNDLE=<not set>\n",
      "          LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib/x86_64-linux-\n",
      "                          gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64::/opt/conda/lib\n",
      "               LD_PRELOAD=<not set>\n",
      "             LIBRARY_PATH=:/opt/conda/lib\n",
      "                     PATH=/opt/conda/bin:/vscode/vscode-server-insiders/bin/linux-\n",
      "                          x64/49b8e2d5410795e5a23a9c6b7f99b97f4afb4b47-insider/bin/remote-cli:/o\n",
      "                          pt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/l\n",
      "                          ocal/bin:/usr/sbin:/usr/bin:/sbin:/bin\n",
      "         PYTHONIOENCODING=utf-8\n",
      "               PYTHONPATH=:/opt/facets/facets_overview/python/\n",
      "         PYTHONUNBUFFERED=1\n",
      "           PYTHONUSERBASE=/root/.local\n",
      "       REQUESTS_CA_BUNDLE=<not set>\n",
      "            SSL_CERT_FILE=<not set>\n",
      "           TESSERACT_PATH=/usr/bin/tesseract\n",
      "\n",
      "     active environment : base\n",
      "    active env location : /opt/conda\n",
      "            shell level : 1\n",
      "       user config file : /root/.condarc\n",
      " populated config files : /opt/conda/.condarc\n",
      "                          /root/.condarc\n",
      "          conda version : 23.3.1\n",
      "    conda-build version : not installed\n",
      "         python version : 3.10.10.final.0\n",
      "       virtual packages : __archspec=1=x86_64\n",
      "                          __glibc=2.31=0\n",
      "                          __linux=5.15.90.1=0\n",
      "                          __unix=0=0\n",
      "       base environment : /opt/conda  (writable)\n",
      "      conda av data dir : /opt/conda/etc/conda\n",
      "  conda av metadata url : None\n",
      "           channel URLs : https://conda.anaconda.org/rapidsai/linux-64\n",
      "                          https://conda.anaconda.org/rapidsai/noarch\n",
      "                          https://conda.anaconda.org/nvidia/linux-64\n",
      "                          https://conda.anaconda.org/nvidia/noarch\n",
      "                          https://conda.anaconda.org/conda-forge/linux-64\n",
      "                          https://conda.anaconda.org/conda-forge/noarch\n",
      "                          https://repo.anaconda.com/pkgs/main/linux-64\n",
      "                          https://repo.anaconda.com/pkgs/main/noarch\n",
      "                          https://repo.anaconda.com/pkgs/r/linux-64\n",
      "                          https://repo.anaconda.com/pkgs/r/noarch\n",
      "          package cache : /opt/conda/pkgs\n",
      "                          /root/.conda/pkgs\n",
      "       envs directories : /opt/conda/envs\n",
      "                          /root/.conda/envs\n",
      "               platform : linux-64\n",
      "             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.10.10 Linux/5.15.90.1-microsoft-standard-WSL2 ubuntu/20.04.6 glibc/2.31\n",
      "                UID:GID : 0:0\n",
      "             netrc file : None\n",
      "           offline mode : False\n",
      "\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n",
      "If submitted, this report will be used by core maintainers to improve\n",
      "future releases of conda.\n",
      "Would you like conda to send this report to the core maintainers? [y/N]: ^C\n",
      "\n",
      "Timeout reached. No report sent.\n",
      "\n"
     ]
    }
   ],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
